name: Monitor Target Size Stock

on:
  schedule:
    # 每 10 分钟运行一次
    - cron: '*/10 * * * *'
  workflow_dispatch: # 支持网页端手动点击测试

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 curl_cffi

      # - name: Check PDP Real Content
      #   run: |
      #     curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" \
      #       "https://arcteryx.com/fr/fr/shop/womens/gamma-mx-hoody-9456" | grep -o "Gamma Mx Hoody" | head -n 1 || echo "Blocked by JS Shield" 
            
      - name: Run Stock Scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python stock_monitor.py

      - name: Commit and push state
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f state_stock.json ]; then
            git add state_stock.json
            git commit -m "Update stock monitor state [skip ci]" || exit 0
            git pull --rebase
            git push
          fi
